
platform :ios, '10.0'
use_frameworks!

target 'OnebyteSwiftNetworkCycle_Example' do

  pod 'Alamofire', '~> 4.0'
  pod 'OnebyteSwiftNetworkCycle', '~> 0.2.0'
  
  target 'OnebyteSwiftNetworkCycle_Tests' do
    inherit! :search_paths

    
  end
end
