use_frameworks!

target 'OnebyteSwiftNetworkCycle_Example' do
  pod 'OnebyteSwiftNetworkCycle', :path => '../'

  target 'OnebyteSwiftNetworkCycle_Tests' do
    inherit! :search_paths

    
  end
end
